version: '2.2'

services:
  server:
    build: ./server/
    env_file:
      - .env
    
    ports:
      - "5000:5000"
    
    volumes:
      - ./server/app/:/app/

    networks:
      - pigex
    restart: always

  client:
    build: ./client/
    env_file:
      - .env
    
    ports:
      - "7000:4173"
    
    volumes:
      - ./client/app/:/app/

    networks:
      - pigex

networks:
  pigex: