version: '2.2'

services:
  server:
    build: ./server/
    env_file:
      - .env
    
    ports:
      - "5000:5000"
    
    volumes:
      - ./server/app/:/app/

    restart: always

  client:
    build: ./client/
    env_file:
      - .env
    
    ports:
      - "4173:7000"
    
    volumes:
      - ./client/
